import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';
//TODO: refactor to remove is admin field, magic token field, and secure email field
@Entity()
export class User {
  //TODO: add autogenerated uuid field
  
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ unique: true })
  email: string;

  @Column({ nullable: true })
  magicToken: string;

  @Column({ default: false })
  isAdmin: boolean;
}

//TODO: entity for user mobile device
//TODO: add entity for magic token
//TODO: add entity for user session
//TODO: add entity for user activity
//TODO: add entity for is admin
//TODO: add entity for secure email
//TODO: add entity for user role
//TODO: add entity for user permission


